trigger:
- main  # Or your branch name

pool:
  name: 'local pc'  # Your self-hosted agent name

variables:
  imageName: 'nginx-custom'
  imageTag: 'v1'
  dockerRegistryServiceConnection: 'dockerhub-azuredevops'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image to Docker Hub'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: 'sksarvar/$(imageName)'  # 👈 Your actual Docker Hub username
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)



