trigger:
- main  # Or your branch name

pool:
  name: 'local pc'  # Your self-hosted agent name

variables:
  dockerHubUsername: 'sksarvar'
  imageName: 'nginx-custom'
  imageTag: 'v1'
  dockerRegistryServiceConnection: 'dockerhub-azuredevops'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image to Docker Hub'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: '$(dockerHubUsername)/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)

- script: |
    echo "Pulling image..."
    docker pull $(dockerHubUsername)/$(imageName):$(imageTag)

    echo "Stopping existing container if exists..."
    docker rm -f nginx-custom || true

    echo "Running container..."
    docker run -d --name nginx-custom -p 8080:80 $(dockerHubUsername)/$(imageName):$(imageTag)
  displayName: 'Deploy Docker Container on Local PC'




