trigger:
- main  # Or your target branch

pool:
  name: 'Default'  # Use the correct agent pool name for your local PC agent

variables:
  imageName: 'nginx-custom'
  imageTag: 'v1'
  dockerRegistryServiceConnection: 'dockerhub-azuredevops'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image to Docker Hub'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(DOCKER_HUB_USERNAME)/$(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)


