apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-custom
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      containers:
      - name: nginx-custom
        image: sksarvar/nginx-custom:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-custom-service
spec:
  selector:
    app: nginx-custom
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: NodePort
